version: '3.7'

services:
  node: &node
    build:
      context: .
    volumes:
      - .:/home/app
  runner:
    <<: *node
    command: /bin/sh
  server:
    <<: *node
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev:inspect
